import { Subscription, ProductWithPrices } from '@/types/subscriptions'

export const basic: ProductWithPrices = {
    active: true,
    description: 'Basic subscription',
    id: 'prod_J1Z2X2Z2X2Z2X2',
    image: null,
    metadata: null,
    name: 'Basic',
    default_price: null,
    prices: [
        {
            active: true,
            currency: 'gbp',
            description: 'Basic subscription monthly',
            id: 'price_1MJQawAibJqcowQPx7T90q2E',
            metadata: null,
            product_id: 'prod_J1Z2X2Z2X2Z2X2',
            type: 'recurring',
            unit_amount: 500,
            billing_scheme: 'per_unit',
            recurring: {
                aggregate_usage: null,
                interval: 'month',
                interval_count: 1,
                trial_period_days: null,
                usage_type: 'licensed',
            },
        },
        {
            active: true,
            currency: 'gbp',
            description: 'Basic subscription yerly',
            id: 'price_1MLIIuAibJqcowQP3PuewuTX',
            metadata: null,
            product_id: 'prod_J1Z2X2Z2X2Z2X2',
            type: 'recurring',
            unit_amount: 5000,
            billing_scheme: 'per_unit',
            recurring: {
                aggregate_usage: null,
                interval: 'year',
                interval_count: 1,
                trial_period_days: null,
                usage_type: 'licensed',
            },
        },
    ],
}

export const pro: ProductWithPrices = {
    active: true,
    description: 'Pro subscription',
    id: 'prod_J1Z2X2Z2X2Z2X2',
    image: null,
    metadata: null,
    name: 'Pro',
    default_price: null,
    prices: [
        {
            active: true,
            currency: 'gbp',
            description: 'Pro subscription monthly',
            id: 'price_1MJQawAibJqcowQPx7T90q2E',
            metadata: null,
            product_id: 'prod_J1Z2X2Z2X2Z2X2',
            type: 'recurring',
            unit_amount: 1000,
            billing_scheme: 'per_unit',
            recurring: {
                aggregate_usage: null,
                interval: 'month',
                interval_count: 1,
                trial_period_days: null,
                usage_type: 'licensed',
            },
        },
        {
            active: true,
            currency: 'gbp',
            description: 'Pro subscription yerly',
            id: 'price_1MLIIuAibJqcowQP3PuewuTX',
            metadata: null,
            product_id: 'prod_J1Z2X2Z2X2Z2X2',
            type: 'recurring',
            unit_amount: 10000,
            billing_scheme: 'per_unit',
            recurring: {
                aggregate_usage: null,
                interval: 'year',
                interval_count: 1,
                trial_period_days: null,
                usage_type: 'licensed',
            },
        },
    ],
}
